//
// C/C++ MusyX Defines Include
// Generated by DolphinExport 11:45:08 6/5/2001
//


#define	GRPGM_Set		0
#define	GRPSFXgroup		1


#define	SNGgcdemo		0
#define	SNGentrance		1
#define	SNGdome		2
#define	SNGspiral		3
#define	SNGhangar		4
#define	SNGcave		5
#define	SNGcinema		6
#define	SNGmetal		7
#define	SNGcoins		8


#define	SFXjump_oneshot		0
#define	SFXknock_oneshot		1
#define	SFXdoor_oneshot		2
#define	SFXcoin_oneshot		3
